## === build env === ##
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
ARG sourcePath
ARG appName

# Copy csproj and restore as distinct layers
COPY $sourcePath/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY $sourcePath ./
RUN dotnet publish -c Release -o out

## === Build runtime image === ##
FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app

COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet"]

EXPOSE 80
